### ISSUE TITLE
CDEICloudFileSystemDidDownloadFilesNotification not firing

### ISSUE THREAD

**Issue by fdstevex** [drewmccormack/ensembles#101]
The CDEICloudFileSystemDidDownloadFilesNotification notification, which is intended to tell a client application that there is new data available to sync, is not firing.

initiateDownloads: in CDEICloudFileSystem is called when a new file appears, and it looks like is expecting to be called once the download is complete, but this doesn't happen.  After the call to startDownloadingUbiquitousItemAtURL there are no further calls to initiateDownloads: for the file that just appeared in iCloud (i.e., it's not called when the download completes).

**Comment by ylin** [comment]
I am also noticing that this is still happening for me, I get the notifications sometimes, but most of the time it is not fired.

**Comment by drewmccormack** [comment]
Unfortunately there is not that much we can do. We rely on the metadata notifications, and they don't always fire. You should just make sure there are backups, like a timer every few minutes, or syncing when the app becomes active.

Kind regards,
Drew

**Comment by ylin** [comment]
Yes, but with further testing, it's not as bad as I initially thought. Most of the time it does fire.
