### ISSUE TITLE
Allow exclusion of entities and properties

### ISSUE THREAD

**Issue by drewmccormack** [drewmccormack/ensembles#157]
Include userInfo in model for this.

**Comment by movesmyers** [comment]
@drewmccormack Just to be clear, this is still only available in Ensembles 2, correct?

**Comment by drewmccormack** [comment]
Yes, that is correct. We generally don't back port anything, unless it is a bug fix.

**Comment by movesmyers** [comment]
Makes sense. Unfortunately, this was the perfect solution for me implementing Ensembles (since I use externally-stored UIImages in my model that aren't syncing and causing problems, and I could just choose to re-download them on leech on other devices). I'll need to find another way.
