### ISSUE TITLE
Delete not sync bug

### ISSUE THREAD

**Issue by sarunw** [drewmccormack/ensembles#198]
Here is my repo steps:

1. Open idiomatic on device and simulator.
2. Add 2 note on device name d1 and d2.
3. Add 2 note on simulator name s1 and s2.
4. wait until both devices sync and show d1, d2, s1, s2.
5. On device delete s1 and s2, then on simulator delete d1 and d2.

Expected:
No note left

Result:
Sometime there are d1 and d2 or s1 and s2 left on one device.

Note:
This not happen every time in my test, but it can happen after repeat those step 2-3 times.

**Comment by drewmccormack** [comment]
I think I fixed this issue recently. I think it happens when a merge fails during applying the deletions. The release I added on Monday should fix this.

I will update the Idiomatic app too.
