### ISSUE TITLE
Dropbox Sample for Mac

### ISSUE THREAD

**Issue by jintomenachery** [drewmccormack/ensembles#199]
Hi...am not sure whether this question is already asked, i went through the book and issues but couldn't find.

My question is whether there is any sample app which uses ensembles app in OSX to sync over dropbox. Idiomatic for Mac doesn't have dropbox sync feature like Idiomatic for iOS. 

Jinto

**Comment by drewmccormack** [comment]
No sample app for that, no. It is quite similar to iOS, but authentication works a bit differently. Read the Dropbox Core API README file for OS X. It describes what you need to do to authenticate.
