### ISSUE TITLE
error: -fobjc-arc is not supported on platforms using the legacy runtime

### ISSUE THREAD

**Issue by gatofepe** [drewmccormack/ensembles#202]
I try to use Ensembles in my Mac Osx project, but when I build the project I receive the error:
 -fobjc-arc is not supported on platforms using the legacy runtime.
I use Xcode 4.3 and OSX 10.8.4. 
Any suggestions?

**Comment by drewmccormack** [comment]
Ensembles does require ARC. Sorry I didn't see this issue.
