### ISSUE TITLE
Got DropboxSDK.h file not found on Xcode7.1

### ISSUE THREAD

**Issue by sarunw** [drewmccormack/ensembles#206]
I install ensembles using cocoapods and got `DropboxSDK.h file not found` compile error In CDEDropboxCloudFileSystem.h line 13 #import "DropboxSDK.h"

**Comment by walsht** [comment]
I had to go back to cocoapods 0.37.2 for it to work.
```
sudo gem install cocoapods -v 0.37.2
```
@drewmccormack is aware of the issue.

**Comment by drewmccormack** [comment]
If anyone has an idea how this can be fixed, please let me know. It is clearly a Cocoapods issue. I'm no expert, and all the variations of imports I tried seemed to fail.

**Comment by chbeer** [comment]
No problem here. CocoaPods version 0.39.0

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod "Ensembles", "~> 1.0"
pod "Ensembles/Dropbox", "~> 1.0"
```

Podfile.lock:
```
PODS:
  - Dropbox-iOS-SDK (1.3.13)
  - Ensembles (1.4.1):
    - Ensembles/Core (= 1.4.1)
  - Ensembles/Core (1.4.1)
  - Ensembles/Dropbox (1.4.1):
    - Dropbox-iOS-SDK
    - Dropbox-OSX-SDK
    - Ensembles/Core

DEPENDENCIES:
  - Ensembles (~> 1.0)
  - Ensembles/Dropbox (~> 1.0)

SPEC CHECKSUMS:
  Dropbox-iOS-SDK: e0c9b08d1604b39cb78c1d0333251de0f6bdec60
  Ensembles: 90013c435ff874a7a9ccb7a334b74b93ac53dc12

COCOAPODS: 0.39.0
```

**Comment by chbeer** [comment]
Are you using `use_frameworks!`?

**Comment by walsht** [comment]
Same here.  The latest version of ensembles and cocoa pods works for me now.

**Comment by drewmccormack** [comment]
Seems may have been a glitch in Cocoapods. Closing.

**Comment by 3rdcycle** [comment]
This keeps popping up for me. It's really weird I've tried reinstalling pods, downgrading pods (0.37.2) upgrading pods (1.0 beta). 0.37.2 crashed and after switching back to 0.39 it worked exactly **once**. After I stopped the app and clicked 'run' again, the error was back without me having made any changes in the project whatsoever. Really weird.
