### ISSUE TITLE
Error in leech

### ISSUE THREAD

**Issue by Spokane-Dude** [drewmccormack/ensembles#207]
Hi Drew... First run, trying to get past the initial leech... I'm getting this error:

`Error in leech: Error Domain=CDEErrorDomain Code=1003 "User is not logged into iCloud." UserInfo={NSLocalizedDescription=User is not logged into iCloud.}`

* I am logged in to iCloud
* running on the latest iOS (9.1), Objective-C and XCode 7.1 and the latest version of ensembles 1.0
* This is the ubiquityContainerIdentifier from the debug run:  
`ubiquityContainerIdentifier	__NSCFConstantString *`	`@"iCloud.com.pragerphoneapps.BookstoreInventoryManager"	0x00155768`
* no build errors (I have -lc and -ObjC parameters in my app, ensembles and pods targets)

What do you think the problem is?

**Comment by drewmccormack** [comment]
Have you setup iCloud for your app at developer.apple.com <http://developer.apple.com/>? You need an iCloud container there.
Did you setup iCloud in the Capabilities tab? You need iCloud Documents. Maybe send me a screenshot.
Also, take a look at the Simple Sync example app, and compare it to your setup.

Drew

**Comment by Spokane-Dude** [comment]
I have the iCloud container, if that's what you are referring to:
![2015-12-07_0955](https://cloud.githubusercontent.com/assets/383775/11635019/d8d6a478-9cc8-11e5-88d9-071eee55f73c.png)
![2015-12-07_0957](https://cloud.githubusercontent.com/assets/383775/11635042/08553250-9cc9-11e5-9393-4200fb4d405c.png)

**Comment by drewmccormack** [comment]
What do you get returned by cloudIdentityToken and the container URL method from NSFileManager? They need to return non-nil values if iCloud is setup properly.

Kind regards,
Drew

**Comment by Spokane-Dude** [comment]
Are you referring to the ubiquityIdentityToken?  If so, this is what is returned:
`ubiquityContainerIdentifier	__NSCFConstantString *	@"iCloud.com.pragerphoneapps.BookstoreInventoryManager"	0x00166768`
If not, I have no idea of what you are referring to; I did a search and found nothing in my app or Simple Sync.

Regards,
Rolf

**Comment by drewmccormack** [comment]
It is a method on NSFileManager. It is standard iCloud, not ensembles.

See the Apple docs for more info.

Once you have iCloud setup and working, Ensembles should then work.

Kind regards,
Drew

**Comment by Spokane-Dude** [comment]
Hi Drew... well, after messing with both the iPad and iMac all day, I have determined that I can access iCloud using the same account on both devices (iPad and iMac) through iCloud.com.  

When I try this code in my app, I get 'nil' for all three methods.
`        id currentiCloudToken = [[NSFileManager defaultManager] ubiquityIdentityToken];
        NSURL *url = [[NSFileManager defaultManager] URLForUbiquityContainerIdentifier:@"iCloud.com.pragerphoneapps.BookstoreInventoryManager"];
        id myContainer = [[NSFileManager defaultManager] URLForUbiquityContainerIdentifier: nil];
`

If I remove the Ensembles code before these three statements, I *still* get nil.  So, what or where do I check next?  I have rebooted the iMac and the iPad;  I'm at a loss now as to what it could be.

Regards, Rolf

**Comment by drewmccormack** [comment]
At this point you are better to Google for iiCloud troubleshooting than actually Ensembles. This is purely an Apple/iCloud issue now.

Here are some things I can think to check:

- Did you go into iCloud Settings on the device and make sure iCloud Drive was turned on?
- Did you add an iCloud container in the provisioning portal?
- Did you add iCloud to your App ID in the provisioning portal at developer.apple.com? (screenshot)


- Is your iPhone registered in the provisioning portal?
- If it still doesn’t work, have you tried creating a development provisioning profile for the app?
- Not sure if this is the case, but is the iCloud account you are trying to test associated with your develop account? Perhaps you need to add it as one of the ‘People’ in your team.
- Googling ‘ubiquityIdentityToken is nil’ returns a lot of hits. This looks useful: https://devforums.apple.com/thread/229509

Drew

**Comment by Spokane-Dude** [comment]
OK, I understand... thanks anyway... :-}

**Comment by Spokane-Dude** [comment]
Hi Drew... Apple Tech Support found the culprit and I thought I would 
pass it on to you to add to your arsenal of tips...

    "When I run codesign tool on your built binary, it’s missing these
    entitlements:

    com.apple.developer.icloud-container-identifiers
    com.apple.developer.icloud-services
    com.apple.developer.ubiquity-container-identifiers

    For some strange reason Xcode is stripping your final entitlements
    of those important keys.

    To fix this, go into Build Settings, and delete the Code Signing
    Entitlements setting, this will in effect remove your old
    entitlements file and revert your iCloud capabilities.  Go back to
    iCloud Capabilities and turn back on iCloud, and re-check the
    “iCloud Document” services again.  This will re-create a new
    entitlements file.  The kicker here is Xcode was showing “Any SDK”
    for the debug target.  By following this fix, (delete and re-add the
    entitlement file), this removes that “Any SDK” setting, which is the
    culprit.

    I verified your project (with my own container ID), and the NSURL is
    valid for the ubiquity container."

I am now able to connect to iCloud on my iPad through my app...

Regards,  Rolf

**Comment by drewmccormack** [comment]
Hi Rolf,
Thanks for sharing this. 
What a mess, huh? So it sounds like a straight up Xcode bug.
Kind regards,
Drew

**Comment by Spokane-Dude** [comment]
They (Apple TS) asked me to submit a RADAR on it... will do when I get some spare time...

**Comment by pronebird** [comment]
This Any SDK thing has been giving a lot of trouble in past years regarding code sign. I can confirm that sometimes it messes things up.

**Comment by sumowesley** [comment]
Just following on from this, I received the same error message (not logged in) and the sequence of deleting and regenerating the iCloud capabilities seems to have got over that hurdle. Many thanks.

**Comment by drewmccormack** [comment]
#resolve
