### ISSUE TITLE
Linker error with Dropbox

### ISSUE THREAD

**Issue by pronebird** [drewmccormack/ensembles#208]
I've got the following error during compilation:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DBRestClient", referenced from:
      objc-class-ref in CDEDropboxCloudFileSystem.o
ld: symbol(s) not found for architecture x86_64
```

I use CocoaPods. Am I right that Dropbox SDK is out of date and simply not built for x86_64?

**Comment by drewmccormack** [comment]
I think it should support x86_64. I have used it in my OS X app.

Did you add Ensembles/DropboxCore in the podfile?

Drew

**Comment by pronebird** [comment]
Hi @drewmccormack ,

Yes I've added both Ensembles and Dropbox:

```
pod 'Ensembles', '~> 1.4.3'
pod 'Ensembles/Dropbox', '~> 1.4.3'
```

I could clearly see `DropboxSDK` is installed during `pod install`.

**Comment by sarunw** [comment]
@pronebird Did you manage to fix this? Got the same error.

**Comment by pronebird** [comment]
@sarunw no unfortunately not.
