### ISSUE TITLE
Handle CDEErrorCodeUnknownModelVersion

### ISSUE THREAD

**Issue by pronebird** [drewmccormack/ensembles#211]
I am obviously developing my app and changing data model pretty often. What is the preferred way to tackle CDEErrorCodeUnknownModelVersion? Speaking of iCloud integration. I'd assume deleting transaction logs from iCloud should be easy.

Roughly, is this enough?

```objc
// forgive me for using defaultManager
BOOL removed = [[NSFileManager defaultManager] removeItemAtPath:[[[NSFileManager defaultManager] URLForUbiquityContainerIdentifier:nil] URLByAppendingPathComponent:cloudFileSystem.relativePathToRootInContainer] error:nil];
```

Thanks.

**Comment by drewmccormack** [comment]
How are you migrating? If you use automatic migration, ensembles will usually work ok. As soon as the user updates, the error will disappear. (In Ensembles 2 this is handled a little nicer; devices not updated can continue to sync with other unupdated devices, and the error does not arise.)

If you are not using auto migration, you need to start a new ensemble for each migration. Just assign a new ensemble identifier eg "MyEnsemble.v2"

The book goes into more detail.

Kind regards,
Drew

**Comment by pronebird** [comment]
During development I don't migrate per se. I just want to drop the entire thing. I'll take a look at the book, thanks!

**Comment by pronebird** [comment]
I read a book and discovered a method on persistent store that removes all files from iCloud.

**Comment by pronebird** [comment]
I use automatic migration and just added a single optional, indexed string attribute to one of entities. However sync still throws 204. I'd expect it would be able to do automatic migration.

```xml
<entity name="SpotlightIndex" representedClassName="SpotlightIndexModel" syncable="YES">
    <attribute name="domain" optional="YES" attributeType="String" indexed="YES" syncable="YES"/>
   <!-- [..] -->
</entity>
```

I setup Ensembles with the same options:

```objc
    CDEPersistentStoreEnsemble *ensemble =
    [[CDEPersistentStoreEnsemble alloc] initWithEnsembleIdentifier:ensembleIdentifier
                                                persistentStoreURL:self.storeURL
                                            persistentStoreOptions:self.storeOptions
                                             managedObjectModelURL:modelURL
                                                   cloudFileSystem:cloudFileSystem
                                         localDataRootDirectoryURL:nil];
```

**Comment by drewmccormack** [comment]
It does handle that.

I suspect you may have messed around with your model during development. If you change your model and test sync, and then change it again, without two full migrations, the sync data will contain an event for a model version that no longer exists.

It is very easy to accidentally do this as you update your model in development. Solution is clearing the cloud data.

This is not a problem with production, because all the model versions will be available.

Kind regards,
Drew

**Comment by pronebird** [comment]
@drewmccormack thanks for answering that fast and on Sunday. I bet you are right.
