### ISSUE TITLE
How to monitor root context with ensembles

### ISSUE THREAD

**Issue by pronebird** [drewmccormack/ensembles#213]
Previously I had a monitoring of root context that would normally catch all changes for specific object and index/deindex it from Spotlight based on what's going on with the object. How can I achieve the same with Ensembles when changes arrive from multiple devices and being merged in background?

Would it be enough to just switch notification observer to `CDEMonitoredManagedObjectContextDidSaveNotification` and `CDEMonitoredManagedObjectContextWillSaveNotification`?

**Comment by drewmccormack** [comment]
If you need to change an object before it gets saved, use the delegate methods. Eg persistentStoreEnsemble:shouldSave... See the book for details.

If you mean how do you ignore notifications from the ensembles saves, just check the context and return if it is an unknown context.

Kind regards,
Drew

**Comment by pronebird** [comment]
Yeah so the thing is, I'd like to pick up added/updated and deleted objects, then update index in Spotlight. So I don't really need to modify objects.

So far I've tried to hook up both will/did save events and `CDEMonitoredManagedObjectContextDidSaveNotification` is never called. `CDEMonitoredManagedObjectContextWillSaveNotification` works though.

```objc
- (void)addObservers { 
    /// ...
    [notificationCenter addObserver:self
                           selector:@selector(ensemblesContextWillSave:)
                               name:CDEMonitoredManagedObjectContextWillSaveNotification
                             object:nil];
    
    [notificationCenter addObserver:self
                           selector:@selector(ensemblesContextDidSave:)
                               name:CDEMonitoredManagedObjectContextDidSaveNotification
                             object:nil];
}

- (void)ensemblesContextWillSave:(NSNotification *)note {
    [self handleWillSaveNotification:note];
}

- (void)ensemblesContextDidSave:(NSNotification *)note {
    [self handleDidSaveNotification:note];
}
```

**Comment by drewmccormack** [comment]
I think you could get that info in the delegate menthods of ensembles. You get passed the context there, and can query for what is changed or about to change. Same goes for the delegate method called just after the save. In fact, these methods are just triggered by the notifications you are observing.

**Comment by pronebird** [comment]
Thanks @drewmccormack ! I'll give it a shot!

**Comment by pronebird** [comment]
Yes you were right. It worked. I had to use `shouldSaveMergedChangesInManagedObjectContext` and `didSaveMergeChangesWithNotification` to monitor changes. The only side effect that I think is if I monitor both Ensembles and my saving context for changes then both are being fired. So maybe I should drop monitoring my own root context and totally rely on Ensembles notifications because merge should always handle with events store, but again I am not sure how it will work in case if iCloud is disabled.
