### ISSUE TITLE
Using Ensembles With CloudKit

### ISSUE THREAD

**Issue by tounekti-ali** [drewmccormack/ensembles#214]
Hello
Is it possible to tell me how to use Core Data with CloudKit .
I did not find the two files
CDECloudKitFileSystem.h and CDECloudKitFileSystem.m in the Framework / Extensions directory
Do you have a Detailed tutorial
Thank you

**Comment by drewmccormack** [comment]
CloudKit is only available in Ensembles v2, I'm afraid. The book explains how to use it, and the quick start chapter is a reasonable tutorial. See also the sample apps.
