### ISSUE TITLE
two Mac OSX apps that shares the same Core Data database

### ISSUE THREAD

**Issue by gatofepe** [drewmccormack/ensembles#216]
Hello, I developed a Mac OSX app based on Core Data.
This database contains a lot of informations like name, phone, mail etc.
Now I would use a copy of this app on another Mac.
Is it possible that the two app share the same database, so the two users can work 
making change to the records in database at the same time?
The two Mac are in the same local LAN.
Can Ensembles make this?
Thanks

**Comment by drewmccormack** [comment]
Yes, it could do that. You could use the Multipeer Connectivity framework to set it up. It would be a bit of work, but it could be done.

If your database was not too big, the changes could go across in a few seconds. If you have a large database, it could be longer.

**Comment by gatofepe** [comment]
Thanks a lot
