### ISSUE TITLE
Does transient properties get sync with ensemble?

### ISSUE THREAD

**Issue by sarunw** [drewmccormack/ensembles#225]
I have transient property on my model, but it doesn't seem to sync this is by design? Can I do anything to make this sync?

**Comment by drewmccormack** [comment]
If it is transient, it won't sync. That would make no sense. It is never stored in the store, so never synced to another store. 

You should make it non transient if it needs to sync. Transients are for in memory variables only used on one device, and discarded on quit.

Kind regards,
Drew
