### ISSUE TITLE
Error merging: Error Domain=CDEErrorDomain Code=201 "(null)"

### ISSUE THREAD

**Issue by vivekpathania** [drewmccormack/ensembles#226]
I am using ensembles in my IOS app with Core Data &  Dropbox . I was was working perfectly till i added a new model (light weight migration) and updated my device to IOS 9.1 . Now it does not pull the old data from DropBox though i can see all the old files are still their in DropBox . I am stuck with this error every time i try to merge  . 

I have even tried deleting the app from one of my device and reinstalling it still it starts fresh and does not pull in the old data . Any help in retrieving the old data  would be just great .

Thanks .

**Comment by drewmccormack** [comment]
That error is usually caused by something only half uploading data. You could clear the cloud data and releech to upload the data again.

To debug, you could use this to see more detail

CDESetLoggingLevel(CDELogLevelVerbose);

Drew

**Comment by drewmccormack** [comment]
If you have data on one device, the easiest solution is to delete Dropbox data and let that device upload.

If the only data you have is in the cloud, you should be careful. Using the verbose logging, you can see which files are a problem. You could move those out of Dropbox, then delete the app, restart the device and install again. With the problem files gone, hopefully it will pull down the data.

Note that this situation should not arise in Ensenbles 2, only in Ensembles v1.

Kind regards,
Drew

**Comment by vivekpathania** [comment]
Thanks Drew that helped me fix the issue and pull the old data from the cloud . 

Its a a great library thanks :-)
