### ISSUE TITLE
NSFetchedResultsController recognized update property as move

### ISSUE THREAD

**Issue by sarunw** [drewmccormack/ensembles#227]
When I edit property, NSFetchedResultsController delegate, `func controller(controller: NSFetchedResultsController, didChangeObject anObject: AnyObject, atIndexPath indexPath: NSIndexPath?, forChangeType type: NSFetchedResultsChangeType, newIndexPath: NSIndexPath?)
`, recognize it type `NSFetchedResultsChangeType` as move not an update.

Is this expected behavior or not?

**Comment by drewmccormack** [comment]
No doubt. It doesn't have to do with Ensembles, but there are some unexpected behaviors in the fetch controller. I remember also being surprised by certain notifications. There is an Apple article showing how to handle it all properly, but it is really not easy.

Kind regards,
Drew

**Comment by pronebird** [comment]
This is a bug in CoreData, there are plenty of issues with FRC when it simply reports wrong changes.
