### ISSUE TITLE
Showing User when Sync is in progress

### ISSUE THREAD

**Issue by RaymondMoay** [drewmccormack/ensembles#230]
Hi. I'm creating an app in swift and I'm using v1 of ensembles to sync. Currently everything works perfectly and I am able to tell the user when local files are merged with cloud data using persistentStoreEnsemble(didSaveMergeChangesWithNotification) delegate, however I would like users to know that syncing is in progress and I don't know how to proceed to do so. 

Thanks!!

**Comment by drewmccormack** [comment]
Remember that your app is the one the calls leech and merge methods to start the syncs. So you know exactly when the sync starts, and can use the completion block to know when it ended.
What you could do is fire a notification just before you call leech or merge, and another in the completion block.

To get percentage progress, I’m afraid you would need Ensembles 2. We added that more recently. (BTW Ensembles 2 is currently half price.)

Kind regards,
Drew

**Comment by RaymondMoay** [comment]
Thanks for the reply! I'm currently just testing ensembles and currently I like it and might be purchasing it soon since Core Data Sync is pretty much deprecated. 

Anyhow, I have one more question.

In my CoreDataStack.swift:

`func persistentStoreEnsemble(ensemble: CDEPersistentStoreEnsemble!, didSaveMergeChangesWithNotification notification: NSNotification!) {
        CoreDataStack.defaultStack.managedObjectContext.performBlockAndWait({ () -> Void in
            CoreDataStack.defaultStack.managedObjectContext.mergeChangesFromContextDidSaveNotification(notification)
        })
        if notification != nil {
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(0.02 * Double(NSEC_PER_MSEC))), dispatch_get_main_queue(), {
                NSLog("Database was updated from iCloud")
                CoreDataStack.defaultStack.saveContext()
                NSNotificationCenter.defaultCenter().postNotificationName("DB_UPDATED", object: nil)
            })
        }
    }`

This is called when merged occurred and I used it to stop an animation showing that syncing is still in progress. However, when the app is already updated, merging does not occur and no notification is fired, so I can't stop the syncing animation.  Is there a way to know when data is already synced and no merge will occur so I can fire another notification telling the syncView to stop animating?

**Comment by drewmccormack** [comment]
A better place to put the notification is in the completion block of the mergeWithCompletion: That always gets called.

Drew
