### ISSUE TITLE
Deleting objects in reparationContext

### ISSUE THREAD

**Issue by pronebird** [drewmccormack/ensembles#235]
Hi,

I am using 
```objc
- (BOOL)persistentStoreEnsemble:(CDEPersistentStoreEnsemble *)ensemble shouldSaveMergedChangesInManagedObjectContext:(NSManagedObjectContext *)savingContext reparationManagedObjectContext:(NSManagedObjectContext *)reparationContext
```

 to de-duplicate and merge objects before they make it to Core Data store.

Merge looks as following (sourceObject is a duplicate object, and mergedObject is the object that I will retain in database after de-duplication):

I find all objects in database matching certain value, e.g. Category with name Groceries. Then I choose the object that I would like to keep in database and start merging other objects with it, after merge completed, I delete all duplicates.

```objc
NSManagedObject *retainedObject = [self retainedObjectFromDuplicateObjects:similarObjects];

NSParameterAssert(retainedObject);

// remove retained object from duplicates
NSMutableArray *duplicateObjects = [similarObjects mutableCopy];

[duplicateObjects removeObject:retainedObject];

[duplicateObjects enumerateObjectsUsingBlock:^(NSManagedObject *duplicateObject, __unused NSUInteger idx, __unused BOOL *stop) {
    [mergeResolver mergeObject:duplicateObject intoObject:retainedObject];
}];

[duplicateObjects MR_deleteEntitiesInContext:reparationContext];
```

```objc
[entityDescription.attributesByName enumerateKeysAndObjectsUsingBlock:^(NSString *key, __unused NSAttributeDescription *attr, __unused BOOL *stop) {
    id oldValue = [mergedObject valueForKey:key];
    id newValue = [sourceObject valueForKey:key];

    // because CoreData produces change even when we set the same value
    // it's a good practice to at least check equality with isEqual:
    // before using setter
    if(![oldValue isEqual:newValue]) {
        [mergedObject setValue:newValue forKey:key];
    }
}];

[entityDescription.relationshipsByName enumerateKeysAndObjectsUsingBlock:^(NSString *key, NSRelationshipDescription *relation, __unused BOOL *stop) {        
    if(relation.isToMany) { // to-many
        if(relation.isOrdered) {
            // ... not used
        } else {
            NSSet *oldRelatedObjects = [mergedObject valueForKey:key];
            NSSet *newRelatedObjects = [sourceObject valueForKey:key];
            NSMutableSet *combinedRelatedObjects = [[NSMutableSet alloc] init];

            [combinedRelatedObjects unionSet:oldRelatedObjects];
            [combinedRelatedObjects unionSet:newRelatedObjects];

            // reset relationship to avoid any delete rules to trigger
            [sourceObject setValue:[NSSet set] forKey:key];

            if(![oldRelatedObjects isEqualToSet:combinedRelatedObjects]) {
                [mergedObject setValue:[combinedRelatedObjects copy] forKey:key];
            }
        }
    } else { // to-one
        NSManagedObject *oldRelatedObject = [mergedObject valueForKey:key];
        NSManagedObject *newRelatedObject = [sourceObject valueForKey:key];

        // reset relationship to avoid any delete rules to trigger
        [sourceObject setValue:nil forKey:key];

        if(oldRelatedObject != newRelatedObject) {
            [mergedObject setValue:newRelatedObject forKey:key];
        }
    }
}];
```

All of it happens in reparation context using performBlockAndWait.

However what happens is that all relationships in duplicated objects are being deleted too (as a part CASCADE deletion rule I suppose), even though I copy all of relationships over to the single object (mergedObject) that I would like to keep in database after de-duplication and nullify the relationship on duplicates.

If I do not remove duplicates then everything is fine and all relationships are properly reassigned to the single object, however I end up with a bunch of duplicates dangling around... 

I have a feeling that Ensembles picks up deletions but does not save changes and so instead all of objects go through revision as being deleted.

**Comment by drewmccormack** [comment]
Is it possible you have cascade rules that are causing the deletions?

**Comment by pronebird** [comment]
@drewmccormack I have CASCADE deletion rule set for optional to-many relationship.

Category <-> Expenses.

However when I merge Category objects together, I move all of Expenses over to the single Category and set empty set on relationship in duplicate Categories. Am I being naive that setting empty NSSet on relationship doesn't cause delete rules to fire?

**Comment by pronebird** [comment]
It does not seem that processPendingChanges does anything...

Before FRC receives "delete" event, I see the following in console:

CoreData: warning: An NSManagedObjectContext delegate overrode fault handling behavior to silently delete the object with ID '0xd000000000240002 <x-coredata://97993C27-2D56-4BF2-9B9F-269D9A3C4402/Expense/p9>' and substitute nil/0 for all property values instead of throwing.

Looking at updatedObjects, deletedObjects of reparationContext, everything is alright and my merge updated relationships properly. Moreover inverse relationships are correct too. "DidSave" from Ensembles returns notification with proper "deleted" and "updated" keys. Something tells me I access stale object somewhere... :-)

**Comment by drewmccormack** [comment]
Are you accidentally taking objects in the savingContext and using them in the reparationContext? You can take the objectIDs, but can’t use the objects directly. You would have to use objectWithID: to get the objects again in the reparationContext.

If you are accidentally accessing an object in the wrong place, the newish Core Data debug launch arguments may find it for you.

Drew

**Comment by pronebird** [comment]
I use objectIDs only, It could be I picked up object ID that was removed during reparation. All notifications from ensembles seem fine, however after merge sometimes objects remain in strange state, such as category on one of repaired expenses is suddenly nil (required relationship...).

Out of curiosity I ran: 

```
po [object hasPersistentChangedValues]
NO
```

```
po [object validateForUpdate:nil]
NO
```

But all I do is merge changes from ensemble:

```objc
- (void)persistentStoreEnsemble:(CDEPersistentStoreEnsemble *)ensemble didSaveMergeChangesWithNotification:(NSNotification *)notification {
    if(ensemble != self.ensemble) {
        return;
    }
    
    [self.savingContext performBlockAndWait:^{
        [self.savingContext mergeChangesFromContextDidSaveNotification:notification];
    }];
    
    [self.context performBlockAndWait:^{
        [self.context mergeChangesFromContextDidSaveNotification:notification];
    }];
```

**Comment by pronebird** [comment]
I don't know if that's coincidence, but moving deduplication in `-didSaveMergeChangesWithNotification:` did the trick for me. Leaves me wonder...

**Comment by drewmccormack** [comment]
I wouldn't be surprises if the problem is the background saving context. I pulled that out of my app because I saw some very odd behavior at times.

Deduping in the did-save or completion block should work fine.

**Comment by pronebird** [comment]
Thanks for trying to help me.

My last guess is that I observe NSManagedObjectContextDidSaveNotification/WillSaveNotification on root context quite a lot. I may be wrong but it looks to me that I merge changes while Ensembles is repairing stuff and then I end up with unsaved root context, which when saved, fires deletion of objects that are kind of stuck in some state when they are not really valid for save and have been changed in persistent store but never refreshed because of wrong merge. 

That's why when I end up with empty category on my model and if I restart the app, everything is fine. I am not sure what alternative I can use to catch up with ensembles. The book mentions `CDEMonitoredManagedObjectContextXXXSaveNotification`s but they don't contain information regarding changes which I need to do the proper update.

I pulled out all the pieces that were processing objects upon didSave and things are back to normal. However, I still do merge things in didSave therefore I have to get rid of those too and replace them with equivalent CDE notifications...

**Comment by drewmccormack** [comment]
Ah, right, yes. What I do is just check if the saving context is one I know about, and otherwise return. For example, I check if the PSC is the one on my main context, and if not, I do not merge the changes.

**Comment by pronebird** [comment]
I had a genius piece of code... apparently merging *everything* into saving context. I have no idea how all of that worked before.

```objc
NSManagedObjectContext *context = [stack savingContext];
[context MR_observeContextDidSave:context.parentContext];
```

Thanks for all your help! Such a shame though that it turned out to be my own mistake :/ Ensembles still work!
