### ISSUE TITLE
Detect changes coming from merge

### ISSUE THREAD

**Issue by pronebird** [drewmccormack/ensembles#236]
Hi,

Is there any reliable way to capture changes coming after sync. I specifically want to find out which objects and which properties were changed during sync.

I hooked up both `CDEMonitoredManagedObjectContextWillSaveNotification` and `CDEMonitoredManagedObjectContextDidSaveNotification` but `CDEMonitoredManagedObjectContextDidSaveNotification` is not always called.

I put the breakpoint in `contextDidSave` and it is not fired most of the time, however willSave is always fired.

i.e. 

```objc
NSNotificationCenter *notificationCenter = [NSNotificationCenter defaultCenter];

[notificationCenter addObserver:self
                       selector:@selector(contextWillSave:)
                           name:CDEMonitoredManagedObjectContextWillSaveNotification
                         object:nil];

[notificationCenter addObserver:self
                       selector:@selector(contextDidSave:)
                           name:CDEMonitoredManagedObjectContextDidSaveNotification
                         object:nil];

- (void)contextWillSave:(NSNotification *)note {
    if(![self _shouldReportChanges]) {
        return;
    }
    
    CDEPersistentStoreEnsemble *ensemble = [note.userInfo objectForKey:@"persistentStoreEnsemble"];
    NSManagedObjectContext *context = [note object];
    
    if(self.cdStack.ensemble != ensemble) {
        return;
    }
    
    NSMutableDictionary *changes = [self.changesByKey mutableCopy];
    
    NSLog(@"changes: %@", changes);
    
    [[context updatedObjects] enumerateObjectsUsingBlock:^(NSManagedObject *object, __unused BOOL *stop) {
        if([object.entity.name isEqualToString:[OptionModel entityName]]) {
            NSString *optionKey = [object valueForKey:OptionModelAttributes.name];
            NSDictionary *oldValues = [object committedValuesForKeys:@[ OptionModelAttributes.value ]];
            NSDictionary *newValues = [object changedValues];
            
            // ....
        }
    }];
    
    self.changesByKey = [changes copy];
}

- (void)contextDidSave:(NSNotification *)note {
    if(![self _shouldReportChanges]) {
        return;
    }
    
    CDEPersistentStoreEnsemble *ensemble = [note.userInfo objectForKey:@"persistentStoreEnsemble"];    
    if(self.cdStack.ensemble != ensemble) {
        return;
    }
    
    NSDictionary *changedKeys = [self.changesByKey copy];
    
    // ...
}
```

**Comment by drewmccormack** [comment]
Those notifications are fired when *your* context saves, not the Ensembles context.

There are delegate methods on CDEPersistentStoreEnsemble that can be used to get what changed. Look for persistentStoreEnemble:didSaveMerge…

Drew

**Comment by pronebird** [comment]
Ah now it makes sense. Since both reparation and saving contexts are passed during merge, is it legit to call save on reparation context to get all of changes pop to saving context so I could capture all of the changes? Or Ensembles expects reparation context to be unsaved?

**Comment by drewmccormack** [comment]
You should not save any of the contexts. Ensembles uses the unsaved state to create data for syncing. It has to be able to go through the changes in the reparation context before saving it.

If you just care about what changed overall, use the did-save delegate method. The should-save one, with the reparation context, has changes spread over contexts, and the changes are not saved.

Drew

**Comment by pronebird** [comment]
I need to capture old value for specific entity, so I can make a proper transition in business logic of the app. I guess I will have to go through root and then reparation contexts to collect updates.

**Comment by drewmccormack** [comment]
Are you actually making changes in the reparation context? If you don’t make any, all the changes will be in the saving context.

Drew

**Comment by pronebird** [comment]
@drewmccormack I do de-duplication in reparation context. My theory is, I can collect updated objects by going through savingContext changes first then through reparationContext changes. I can probably make use of NSSet's intersection method to exclude deleted objects during reparation.

**Comment by pronebird** [comment]
@drewmccormack thank you for all your suggestions. Is there any particular reason why CDEMonitoredManagedObjectContextDidSaveNotification hides the normal userInfo keys that usually come with NSManagedObjectContextDidSave such as NSInsertedObjectsKey, NSUpdatedObjectsKey, and NSDeletedObjectsKey?

**Comment by pronebird** [comment]
Closing this issue because delegate provides sufficient functionality to capture changes coming from other device.

**Comment by pronebird** [comment]
It's better to hook up to NSManagedObjectContextDidSave from `shouldSaveMergedChangesInManagedObjectContext ` and once it happens, grab changes from saving context. Ensembles saves reparation context shortly after `shouldSaveMergedChangesInManagedObjectContext`.
