### ISSUE TITLE
tvOS? watchOS? Anyone tried?

### ISSUE THREAD

**Issue by debriennefrancoisjean** [drewmccormack/ensembles#241]
I'd like to know if anyone has used Ensembles with watchOS or tvOS. I know the standard library doesn't provide these targets out of the box but maybe someone has tested this?

**Comment by drewmccormack** [comment]
I don't know of anyone doing this yet. I think it will only be possible after iOS 10, because I think they are only adding CloudKit support now.

Kind regards,
Drew

**Comment by drewmccormack** [comment]
There is now a framework for tvOS in Ensembles 2, though it has not been widely tested.

**Comment by UberJason** [comment]
Howdy! Just wondering if there are plans for Ensembles 1.x to get watchOS support? (Or Ensembles 2? I don't have Ensembles 2 so I can't check if it's already available and I just don't know about it.)

**Comment by drewmccormack** [comment]
Ensembles 2 already has a watchOS framework. Currently no plans to back port to Ensembles 1, but I think it would probably work with very little trouble. Just make a watchOS target framework, add the source files (except Extensions), and it should work.
