### ISSUE TITLE
CDEEEventIntegrator mergeEventsWithCompletion:_block_invoke.91 Causing App Crash

### ISSUE THREAD

**Issue by JDSX** [drewmccormack/ensembles#244]
My project was already up and running using Ensembles however once I migrated to Swift 3 my app now crashes. However the errors all point to the framework when debugging. I keep seeing the following error in the console when syncing;

> Could not load any Objective-C class information. This will significantly reduce the quality of type information available.

or when I leave the app running I get the following memory issue

> Message from debugger: Terminated due to memory issue

And when I dig further using instruments I found that the CPU over 100%, and memory and energy impact both high. When the app crashes It takes me to `CDEEventIntegrator` class, `mergeEventsWithCompletion` function and the dispatch line for `"integrate on background queue".

Im unsure how to resolve this error, and I even turned iCloud drive for the app off in settings however the app still crashes sometime after launching. I have found with iCloud ManagedObjects would keep duplicating. 

Here's my Swift 3 functions in the appDelegate. 

```
    // MARK: Ensembles
    
    var cloudFileSystem: CDECloudFileSystem!
    var ensemble: CDEPersistentStoreEnsemble!
    
    func syncWithCompletion(completion:@escaping (_ completed:Bool) -> Void) {
        
        if !ensemble.isLeeched {
            ensemble.leechPersistentStore { error in
                if error != nil {
                    print("cannot leech \(error!.localizedDescription)")
                    completion(false)
                }
                else {
                    print("leached!!")
                    completion(true)
                }
            }
        }
        else {
            ensemble.merge{ error in
                if error != nil {
                    print("cannot merge \(error!.localizedDescription)")
                    completion(false)
                }
                else {
                    print("merged!!")
                    completion(true)
                    //NSNotificationCenter.defaultCenter().postNotificationName("Updated-DB", object: nil)
                }
            }
        }
    }
    
    func persistentStoreEnsemble(_ ensemble: CDEPersistentStoreEnsemble, didSaveMergeChangesWith notification: Notification) {
        managedObjectContext.performAndWait {
            print("Database was updated from iCloud")
            self.managedObjectContext.mergeChanges(fromContextDidSave: notification as Notification)
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "Updated-DB"), object: nil)
        }
    }
    
    private func persistentStoreEnsemble(ensemble: CDEPersistentStoreEnsemble!, globalIdentifiersForManagedObjects objects: [AnyObject]!) -> [AnyObject]! {
        return (objects as NSArray).value(forKeyPath: "uniqueIdentifier") as! [AnyObject]
    }
```

This is what I am seeing in the console 

<img width="1024" alt="screen shot 2016-09-12 at 17 16 51" src="https://cloud.githubusercontent.com/assets/5117290/18445163/23e7d388-7914-11e6-8e9d-87ed2597fa44.png">

As mentioned the project was working in previous versions of Swift, but now that my functions have been migrated to Swift 3 I am getting the errors mentioned. Does anyone have any ideas why this might be happening ? 

PS: I was actually running final tests before submitting my app for iOS 10 and unfortunately this issue has prevented that. Weird how I haven't had any issues until today

**Comment by drewmccormack** [comment]
I am fairly sure we fixed this a couple of weeks ago. What version of the code do you have?

You should either download the latest code using the link you received when you purchased, or — if you have access to the github repo — update to the latest master branch.

Kind regards,
Drew

**Comment by JDSX** [comment]
Unfortunately I am using the latest release. I even updated today, removed the project app from both devices, cleared iCloud data and started fresh to see what would happen. At first neither device would sync with the error `cannot merge The operation couldn’t be completed. (CDEErrorDomain error 101.)` then the got runtime crashes with the error `warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.`

**Comment by drewmccormack** [comment]
I just updated the Simple Sync example to Swift 3, and it seems to be working OK.

Maybe it is worth trying to run your project with the Zombies enabled, to see if that gives us a clue.

**Comment by drewmccormack** [comment]
Ah, I just realised you are using the open source Ensembles. Is that right? There may well still be a problem there. I have only been updating Ensembles 2.

I will see if I can bring back the relevant changes to the open source project. Setting Zombies would still help to confirm this.

**Comment by JDSX** [comment]
Yes I am, oh right that makes sense. I wanted to get familiar with the open source framework, however I have just purchased Ensembles 2 because 1 has served me well for a few months, and with Swift 3 support and CloudKit the upgrade makes sense. Will try to update my project and hopefully everything will run smooth again

**Comment by JDSX** [comment]
How can I get access to the Simple Sync project in Swift 3 ?

**Comment by drewmccormack** [comment]
It’s currently only in the github repo master branch. If you send me your github username, I will give you access.

Drew

**Comment by JDSX** [comment]
I just actually sent over an email but my username is JDSX, do you have any CloudKit examples in Swift yet ?

**Comment by drewmccormack** [comment]
Just added you to repo.

No, we only have the Simple Sync example in Swift. The Idiomatic example (ObjC) does include CloudKit. Should only be small differences in Swift.

**Comment by smallhorse1987** [comment]
I still have this problem with v1.6. 
Xcode8+iCloud

**Comment by drewmccormack** [comment]
Can you turn on Zombies in your app and tell me where it is crashing? This info is a bit vague at the moment.

**Comment by smallhorse1987** [comment]
Well, I will collect more information tomorrow. 

So far, I rollback to Xcode7, then the issue is gone.

**Comment by smallhorse1987** [comment]
**Pre-condition:**
1，compiled by Xcode8.
2,  refresh installation
3,  turn app to foreground quickly right after it switch to background.

**Debug Infomation:**
![default](https://cloud.githubusercontent.com/assets/18483946/19373422/5f8a79ae-91f6-11e6-8a32-92e5bb21c554.png)

**Zombie debug info：
-[NSError retain]: message sent to deallocated instance 0x174c420a0

**Comment by drewmccormack** [comment]
Is that the release version (1.6)? If possible, can you pull the latest trunk from GitHub? I made a bunch more improvements to NSError handling, and I think I caught that one.

**Comment by drewmccormack** [comment]
Just checked. Yes, I did change that code. See very end of this commit: https://github.com/drewmccormack/ensembles/commit/bedc3f8adfe3c617ef439025a2797278721764dd <https://github.com/drewmccormack/ensembles/commit/bedc3f8adfe3c617ef439025a2797278721764dd>

Drew

**Comment by mastro35** [comment]
yep, 1.6.1 solve the problem. Unfortunately the version provided by CocoaPods is still the 1.6 so be sure to get the latest version from here by using in your PodFile

`    pod 'Ensembles', :git => 'https://github.com/drewmccormack/ensembles.git'

**Comment by drewmccormack** [comment]
Sorry, somehow must have forgotten to push the update. Now done.

**Comment by DAEUN-pixo** [comment]
@drewmccormack Hello... I still have this problem in latest ensembles 😢 
My podfile is configured like @mastro35 

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/69830197/128800920-4aa9daa3-a4e1-4a81-9aac-7cc2d5a7a85c.png">

**Comment by drewmccormack** [comment]
That doesn't look like the same problem. Not also that this thread is from 5 years ago, so unlikely.

Looking at your error, it seems that Ensembles thinks it has NSData, and it actually has an NSArray. Do you have transformable attributes? In particular, an array of values that you are transforming to data?

**Comment by DAEUN-pixo** [comment]
Thank you for quick response :)

As you said, I have transformable attributes. And the type of the array is `[Date]`.
I don't know why this error happed 😢

**Comment by drewmccormack** [comment]
What is the transformer you are using? Can you screenshot the attribute in the Core Data model?

**Comment by drewmccormack** [comment]
I think I see the problem. This was changed by Apple. We have a fix for the change in Git, but it hasn't yet been released for Cocoapods yet.

I will try to release that in the coming days. For now, if you are able to use the HEAD of the Git repo, that should work.

Eg. 
```
pod 'Ensembles', :git => 'https://github.com/drewmccormack/ensembles.git', :commit => 'db261baa0a532408637a594055b0396fae15a91a'
pod update
```

**Comment by DAEUN-pixo** [comment]
I applied your suggestion, but another crash is occurs.. 😢 
My CoreData model has a to-many relationship, and one attribute of the entity is transformable, optional, and the type is `[Date]`. 
I also used `CDEPropertyChangeValueTransformer` for configure Transformer filed :)

> Additionally, the completion of `CDEEnsemble.merge` method is not called.. So `CDEEventIntergrator.mergeEventsWithCompletion` works on private thread. This is identified as the cause of the increased memory usage and cpu usage of my app. Enabling ensemble uses significantly more resources than disabling it.

<img width="1767" alt="스크린샷 2021-08-12 오전 9 44 28" src="https://user-images.githubusercontent.com/69830197/129121375-045da614-9b2e-4505-839b-5e70524bcb67.png">

**Comment by drewmccormack** [comment]
You shouldn't use CDEPropertyChangeValueTransformer. That is an internal transformer. Just use whichever transformer you were using before.

I'm not sure about the optional part. I may need to check if we handle that properly. 

You may need to clear all the sync data that was created before the change. It may have the wrong values.
