### ISSUE TITLE
CDEEEventIntegrator mergeEventsWithCompletion:_block_invoke.91 Causing App Crash in open source ensemble

### ISSUE THREAD

**Issue by DmitriDevelopment** [drewmccormack/ensembles#245]
I'm using open source ensemble 1.5.2. I have the same issue in iOS 10 like #244 - CDEEEventIntegrator mergeEventsWithCompletion:_block_invoke.91 Causing App Crash.
As I understood in ensemble 2 this issue fixed. Are you planing fix this issue in open source ensemble? Thanks.

**Comment by drewmccormack** [comment]
We have added a fix in the latest trunk on GitHub. Can you test that? It was committed after 1.5.2.

**Comment by DmitriDevelopment** [comment]
I'll test with last source and inform you about result

**Comment by DmitriDevelopment** [comment]
I tested on several devices, no crashes. All working fine. Thanks.
