### ISSUE TITLE
UIImage Transformables disappearing

### ISSUE THREAD

**Issue by susiej** [drewmccormack/ensembles#248]
IOS 10 swift 3 
Hi, I've been using transformables to save UIImage thumbnails. These all disappeared when I installed ensembles, and after adding them back they seem to stay for a while, then disappear again (I assume when it resyncs). For larger files I am saving as Binary Data with external storage which so far works fine. Other transformables that just contain a small amount of data seem to also be working fine. I haven't sync'd to any other devices, it's just on my Iphone so far, as I'm just trying to get this half working correctly first. I didn't want the thumbnails to be saved externally as I wanted them to be accessed quickly as they are the main images in a long table. Looking in the db on my phone, all the items in the thumbnail column seem to have been set to null.

Is there a size limit for fields that can be synced? Is there anything else I may have missed? I'm completely new to Ensembles.
Thanks

**Comment by susiej** [comment]
I just tried installing on a second device, and it first had an empty database, and when I restarted the program it crashed at:
        BOOL passedChecks = [revisionManager checkRebasingPrerequisitesForEvents:eventsToMerge error:&error];
EXEC_BAD_ACCESS
in the rebaseWithCompletion function.

**Comment by drewmccormack** [comment]
Hi Susie,
I’m not 100% what is wrong here, but I don’t think UIImage is a good transformable to use. It doesn’t seem to conform to NSCoding, so you would at the very least have to make your own transformer. Did you do that?
Also, if you ever make a Mac app, you can’t import your data (no UIImage).
My suggestion is to store as PNG data. UIImage has a method to get the PNGData, and you can put that on disk. 
You could even make a transformer that simply extracts the PNG, or uses it to make a UIImage. 
Hope that helps.
Kind regards,
Drew

**Comment by drewmccormack** [comment]
For completeness, here is a value transformer I found:

https://github.com/BendingSpoons/teleporter-lib-iOS/blob/master/Teleporter/NSValueTransformer%2BUIImage.m <https://github.com/BendingSpoons/teleporter-lib-iOS/blob/master/Teleporter/NSValueTransformer+UIImage.m>

Kind regards,
Drew

**Comment by susiej** [comment]
I had written a transformer class (well, based off other peoples) to transform the UIImage which had been working fine before. I'll switch to storing just the data. I hadn't yet looked at a Mac version of my app, but plan to at some stage (data entry would be much easier). I didn't know you couldn't use UIImage for the Mac, so that is really good to know. Thanks :) Maybe I'll disable ensembles temporarily, then copy my backup database back to my phone, copy the images into a separate column as png/jpg, disable the old column, then try again with ensembles. Thanks for your help :)

**Comment by drewmccormack** [comment]
OK. Best to try to delete any cloud data you have before starting to sync again.

Drew

**Comment by drewmccormack** [comment]
Out of interest, what were you transforming the UIImage to exactly? Ensembles can only handle NSData for a transformable. Core Data may be a bit more lenient, I’m not sure.

Drew

**Comment by susiej** [comment]
Just as Data. I think I may have originally had it as NSData, but when it upgraded to swift 3 it converted to Data. This particular class I originally basically just copied from examples as it was the first transformable I've used. A lot of the thumbnails were generated from jpgs that had been scraped (so far haven't looked much into legal issues of scraping...), which is why they are jpegrepresentation. Is there an advantage of using pngs instead? Here is my transformer class: 

class ImageTransformer: ValueTransformer {
	
	override class func allowsReverseTransformation() -> Bool {
		return true
	}
	
	override class func transformedValueClass() -> AnyClass {
		return Data.self as! AnyClass
	}
	
	override func transformedValue(_ value: Any?) -> Any? {
		if let image = value as? UIImage {
			return UIImageJPEGRepresentation(image, 1.0)
		}
		return nil
	}
	
	override func reverseTransformedValue(_ value: Any?) -> Any? {
		if let data = value as? Data {
			return UIImage(data: data)
		}
		return nil
	}

}

**Comment by susiej** [comment]
Where do you delete the cloud data (without deleting local data)? I have about 200 entries in my db which I really don't want to have to add back in manually.

**Comment by drewmccormack** [comment]
JPEG should be OK, but I have a feeling UIImage(data:) will not recognize it properly without a jpeg extension. That may be the problem you were having.
I think you would need to write the data to file, and use a jpeg extension.
PNG should just work regardless. It is basically the native format.

Drew

**Comment by drewmccormack** [comment]
Best way to clear all data is to deleech on the device, and then use the iCloud Settings to delete the cloud data in iCloud Drive for you app.

That should leave your local data intact on the iPhone. Later, when you start syncing again, it should upload the data again.

Drew
