### ISSUE TITLE
Ensembles does not build with pods any more since 1.6.2

### ISSUE THREAD

**Issue by JeanetteMueller** [drewmccormack/ensembles#250]
Xcode cant find 
#import "CDEDefines.h"

**Comment by drewmccormack** [comment]
I just did a very quick test, setting up a new project, and using Cocoapods to install Ensembles at 1.6.2, and all worked fine. I'm attaching the project here in case it helps.

Some things to check:

1. Is Cocoapods up to date? Use `sudo gem install cocoapods` to update.
2. Look at the header search path for your target in Build Settings. Should include the paths in the attached screenshot.

If anyone else is having this issue, please chip in. And if there is a known solution, even better.

**Comment by drewmccormack** [comment]
One more question: Are you importing `CDEDefines.h` directly? You should generally just import `Ensembles.h`

**Comment by JeanetteMueller** [comment]
xcode glitch :(
