### ISSUE TITLE
Replace Dropbox-iOS-SDK pod dependency with ObjectiveDropboxOfficial

### ISSUE THREAD

**Issue by xjki** [drewmccormack/ensembles#252]
Dropbox API v1 used in Dropbox-iOS-SDK pod will be turned off on [June 28, 2017](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/).
It would be wise to replace it with [ObjectiveDropboxOfficial](https://github.com/dropbox/dropbox-sdk-obj-c) pod that uses Dropbox API v2.

**Comment by drewmccormack** [comment]
I will try to get to this this week. Note that version 2 of Ensembles already has Dropbox API v2 incorporated.

**Comment by xjki** [comment]
https://github.com/drewmccormack/ensembles/commit/e6a7d9b33c7a9f416a59d56125e328ac12ad96f1
