### ISSUE TITLE
Migrate from Dropbox v1 to v2 api's

### ISSUE THREAD

**Issue by Simone67** [drewmccormack/ensembles#254]
Hi Drew,
it should be very appreciate if you will update Read.me including all the steps to migrate from Dropbox Api's V1 to V2
Thank you

**Comment by drewmccormack** [comment]
I don't have a migration guide, but the free manual at http://leanpub.com/ensembles is updated for using Dropbox v2. The last chapter describes the new steps required.

The Idiomatic app is also updated to use the new API. Just searching for Dropbox  should find most of the points in the code that you need to change.
