### ISSUE TITLE
Force rebase?

### ISSUE THREAD

**Issue by susiej** [drewmccormack/ensembles#256]
Hi,
is it possible to force the cloud copy to rebase to what is on my laptop (macos version)? I've stuffed something up and now my merges log the error:
[_NSFaultingMutableSet array]: unrecognized selector sent to instance 0x600000433a00
The merge returns nil error, but it seems to prevent it from completing successfully as the changes aren't propagating. 
If I have to, I can deleech the ios versions, but I didn't want to loose all my data completely. 

Or should I just rename the ensemble store and let it copy itself to a new version? If I did that, what is the best way to wipe the old data so I don't have it lying around? 

Thanks, Susie

**Comment by drewmccormack** [comment]
Hi Susie,
There is a class method on CDEPersistentStoreEnsemble that removes data for an ensemble. +removeEnsemble...
If I understand correctly, your local data is right, and the cloud is wrong. In that case, deleech, then call the above method, then leech again.
Kind regards,
Drew

**Comment by susiej** [comment]
Finally have it working again! Thanks :) It took a nearly week of fiddling around to get it up and running. (Well, in my spare time which isn't that much when I had a work project due on Thursday and have two kids :P).
One of my objects had somehow lost it's uniqueid and it was failing silently. And I discovered that if you use sqlite3 to add the id back in, if the .sqlite-wal file still has data in it the update you make disappears, so you think it's updated, then re-run the program, and the uniqueid disappears again as sqlite/coredata overwrites it *sigh*

**Comment by drewmccormack** [comment]
It is important that Ensembles open the SQLite in the same mode as you are opening it. If you set custom options for your store, pass those same options to Ensembles via the property `persistentStoreOptions`. Don’t know if that could have caused this, but worth considering.

Drew
