### ISSUE TITLE
Block variable instead of CDELogCallbackFunction for logging?

### ISSUE THREAD

**Issue by xjki** [drewmccormack/ensembles#257]
Wouldn't it be better (easier to interop with objective-c)  if instead of using function parameter for CDESetLogCallback block variable would be used instead? Just a suggestion.

**Comment by drewmccormack** [comment]
It may be slightly easier, I guess. It's really a pro feature anyway, which most people will not use, and I think the sort of devs that will want to use that will know how to use function pointers.
