### ISSUE TITLE
migrate to dropboxv2 (sorry to disturb you)

### ISSUE THREAD

**Issue by Simone67** [drewmccormack/ensembles#258]
In your specs:

> Incorporating Ensembles in an iOS Project
> To add Ensembles to your App's Xcode Project with CocoaPods...
> Add the following to your Podfile
> platform :ios, '7.0'
> pod "Ensembles", "~> 1.0"

but when I do: --> pod install
the release installed is 1.6.2 n ot 1.7(with dropboxv2)

I do not download the Ensembles framework but I use Podfile

I'm sorry to disturb you but can't solve the dropboxv2 problem becouse when I do pod install nothing change...

**Comment by xjki** [comment]
Point pods to repo original and specify dependencies:
pod 'ObjectiveDropboxOfficial', '~> 3.0.18'
pod 'Ensembles', :git => 'https://github.com/drewmccormack/ensembles', :branch => 'master'
pod 'Ensembles/DropboxV2', :git => 'https://github.com/drewmccormack/ensembles', :branch => 'master'

**Comment by drewmccormack** [comment]
Also, note that Dropbox v2 now requires iOS 9 or later, so you need to have this line 

`platform :ios, '7.0'`
