### ISSUE TITLE
Carthage support 

### ISSUE THREAD

**Issue by gorbannastya** [drewmccormack/ensembles#263]
Hello. Thank you for this awesome library, it's a huge timesaver!
Do you plan to add Carthage support for the free version?

**Comment by drewmccormack** [comment]
I don't have much experience with Carthage, but I am pretty sure it should already work with Ensembles. We have targets to build frameworks, and as far as I know, you just setup Carthage to build the framework you want (eg Ensembles iOS Module).

**Comment by gorbannastya** [comment]
You're sure, it almost works. The only thing left to do is to make "Ensembles iOS Module" scheme shared. I've crated pull request #264

**Comment by drewmccormack** [comment]
Done. thanks!
