### ISSUE TITLE
Error installing Dropbox-iOS-SDK

### ISSUE THREAD

**Issue by Simone67** [drewmccormack/ensembles#265]
Hello Drew,
In readme file you write to add "pod "Ensembles/Dropbox", "~> 1.0" to include dropbox sync, but I have this error message:

Error installing Dropbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/7s/9pgxb0wx2wq2fk0pc29jjxfc0000gn/T/d20171019-3649-1dytiec/file.zip https://www.dropbox.com/static/developers/dropbox-ios-sdk-1.3.13.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   1363      0 --:--:-- --:--:-- --:--:--  1369
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

and cocoapod stops.
I tried to change **"pod "Ensembles/Dropbox", "~> 1.0"** -->  **pod 'ObjectiveDropboxOfficial'** and the error disappear but then this line do not works anymore: **#import "CDEDropboxCloudFileSystem.h"**
could you help me or fix the problem importing directly from cocoapod?
thank you

**Comment by drewmccormack** [comment]
I'm afraid that info is out of date. Will fix. 

You need to use Dropbox V2. 

    pod"Ensembles/DropboxV2","~>1.0"

See last chapter of free book http://leanpub.com/ensembles
