### ISSUE TITLE
CocoaPods was not able to update the `master` repo

### ISSUE THREAD

**Issue by Spokane-Dude** [drewmccormack/ensembles#266]
I have an app that was written several years ago; I am now in the process of making some changes to it, and needed to update Ensembles to v1.7 (to remove warnings/errors during build).  I followed the instructions in the release notes on GitHub, specifically the section **Downloading Ensembles**.
When doing the _git clone_ command, I couldn't find the updated Ensembles code, so I did a download and unzipped the file, getting a ensembles-master.zip file.  My app's Podfile already contained the two lines of code exactly as listed in the release notes.  When I do the pod update, I get the following results of _pod update --verbose_ command:

> iMac:bookstoreinventorymanager rolfmarsh$ pod update --verbose
Update all pods
  Preparing
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Updating spec repo `master`
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:110:in `rescue in update_git_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:106:in `update_git_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:124:in `update_git_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:334:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/master_source.rb:15:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:220:in `block in update_repositories'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:218:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:218:in `update_repositories'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:146:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:145:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

I have absolutely NO idea what this message is referring to (yes, I checked Google) nor do I know how to go about fixing it.  Help would be greatly appreciated.

SD

**Comment by drewmccormack** [comment]
You shouldn't need to download or use git to get Ensembles if you are using Cocoapods. Cocoapods is designed to fulfill that purpose.

I'm afraid you problem here is with Cocoapods, and not with Ensembles, so I am not an expert there (I don't use it in my projects). My guess is that you should update the versions for Ensembles in the pod file, if necessary, and try the update again. If it fails, google the error, and if all fails, completely remove Cocoapods cache and reinstall it.
