### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by johnheb** [drewmccormack/ensembles#284]
Hello Drew,

Downloaded ensembles the other day and we are very excited about using the v2 product.  We have been using something called Ubiquity Store Manager to Sync with iCloud in our Apps and really need a solution like yours.

We downloaded the master the other day and the Simple Sync project ran flawlessly.  Today we added the ensembles library to our project and it worked.  Somehow, the Ensembles IOS project was removed from the Simple Sync project...

So we downloaded and tried the Master-
Sample twice and get the message below.  We have added a valid bundleID, team and iCloud container.  We are also getting this message with the Mac version.

What would you suggest?

Thanks,

John

/Users/iMac/Library/Developer/Xcode/DerivedData/Simple_Sync-gdtsysfesdfnzncbayhtqxfjwyoi/Build/Intermediates.noindex/Ensembles iOS.build/Debug-iphoneos/Documentation.build/Script-072C2F3618C9FBD900453E78.sh: line 2: /usr/local/bin/appledoc: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

<img width="1300" alt="ensembles error" src="https://user-images.githubusercontent.com/7884891/61659569-f48c3280-ac84-11e9-86c9-f16923a3612d.png">

**Comment by drewmccormack** [comment]
Hi John,
That looks like it is running the documentation target, which requires appledoc be installed. But I think you should be able to build the app and framework with no docs.
Kind regards,
Drew

**Comment by johnheb** [comment]
Thanx Drew!
