### ISSUE TITLE
iOS 14 warning CDEObjectChange.propertyChangeValues is using a nil or insecure value 

### ISSUE THREAD

**Issue by sger** [drewmccormack/ensembles#292]
Hello,

After upgrading to Xcode 12 i'm getting this warning

Ensembles/Framework/Resources/CDEEventStoreModel.xcdatamodeld/CDEEventStoreModel_2.xcdatamodel:CDEObjectChange.propertyChangeValues: warning: CDEObjectChange.propertyChangeValues is using a nil or insecure value transformer. Please switch to NSSecureUnarchiveFromDataTransformerName or a custom NSValueTransformer subclass of NSSecureUnarchiveFromDataTransformer [2]

Is it safe to leave it as it is?

**Comment by drewmccormack** [comment]
Yes, this should be safe. It has actually been there for a year or more.

We have some changes in the master branch to fix this, but there is no release yet. It is just a warning though, so no danger.

**Comment by sger** [comment]
ok thank you @drewmccormack will close the issue.
