### ISSUE TITLE
grantAccessClaim reply is an error

### ISSUE THREAD

**Issue by tjosten** [drewmccormack/ensembles#298]
Hello,

since latest versions of macOS (first seen with 14.4), the system logs of my application (using Ensembles 1.10) is full of logs like:

```
grantAccessClaim reply is an error: Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={NSLocalizedDescription=The file couldn’t be opened.}
grantAccessClaim reply is an error: Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={NSUnderlyingError=0x600001218a20 {Error Domain=libfssync.MaterializationError Code=3 "materializationFailed" UserInfo={NSLocalizedDescription=materializationFailed}}}
```

Also, the application constantly utilises CPU time, that I was able to profile down to Ensembles. Any idea of what's happening here? Please let me know if you need more information.

**Comment by tjosten** [comment]
After looking at a source for the error in my implementation for quite a long time, I finally tried to delete all local iCloud data. It seems there was inconsistency in that data, since they have been redownloaded, the error is gone. Weird.

**Comment by drewmccormack** [comment]
Very odd. Does sound like something went wrong with iCloud on the device. Perhaps try a restart if you see it again.
